import { useAuth } from "@hooks/useAuth";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const { user } = useAuth();
  console.log(user?.token);

  const getAWSapi = async () => {
    try {
      const response = await fetch(
        "https://s2ipmgcsy5.execute-api.us-east-1.amazonaws.com",
        {
          headers: {
            Authorization: user?.token ?? "",
          },
        }
      );
      const message = await response.json();
      console.log(message);
    } catch (error) {
      console.log(error);
    }
  };

  const getHello = async () => {
    try {
      const response = await fetch("/api/hello");
      const message = await response.json();
      console.log(message);
    } catch (error) {
      console.log(error);
    }
  };

  const getGoodbye = async () => {
    try {
      const response = await fetch("/api/goodbye");
      const message = await response.json();
      console.log(message);
    } catch (error) {
      console.log(error);
    }
  };

  const getAuth = async () => {
    const res = await fetch("/api/auth", {
      headers: new Headers({ Authorization: user?.token ?? "poggies" }),
    });
    const message = await res.json();
    console.log(message);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        welcome!
        <br />
        <button onClick={getAWSapi} type="button">
          AWS API
        </button>
        <button onClick={getHello} type="button">
          Hello
        </button>
        <button onClick={getGoodbye} type="button">
          Goodbye
        </button>
        <br />
        <button type="button" onClick={getAuth}>
          Click to ping <pre>/api/auth</pre>
        </button>
      </main>
    </div>
  );
};

export default Home;
