const ENVIRONMENT_VARIABLES_FIREBASE_CLIENT = {
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env
    .NEXT_PUBLIC_FIREBASE_API_KEY as string,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env
    .NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN as string,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_PROJECT_ID as string,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env
    .NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET as string,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID as string,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env
    .NEXT_PUBLIC_FIREBASE_APP_ID as string,
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID as string,
};

const ENVIRONMENT_VARIABLES_FIREBASE_ADMIN = {
  FIREBASE_ADMIN_CLIENT_EMAIL: process.env
    .FIREBASE_ADMIN_CLIENT_EMAIL as string,
  FIREBASE_ADMIN_PRIVATE_KEY: process.env.FIREBASE_ADMIN_PRIVATE_KEY as string,
  FIREBASE_ADMIN_PROJECT_ID: process.env.FIREBASE_ADMIN_PROJECT_ID as string,
  FIREBASE_ADMIN_ISSUER: process.env.FIREBASE_ADMIN_ISSUER as string,
  GOOGLE_APPLICATION_CREDENTIALS: process.env
    .GOOGLE_APPLICATION_CREDENTIALS as string,
};

export const ENVIRONMENT_VARIABLES = {
  ...ENVIRONMENT_VARIABLES_FIREBASE_CLIENT,
  ...ENVIRONMENT_VARIABLES_FIREBASE_ADMIN,
};
